// GENERATED by `npm run bake` (scripts/bake-library.ts) — do not edit by hand.
import type { CustomGeometry } from "./customGeometry";
/** Baked shapes follow the built-in shapes (0..29) and the live custom field (30). */
export const BAKED_FORMATION_START = 31;
/** Designer custom formulas baked into built-in shapes: formation 31 + index. */
export const BAKED_SHAPES: readonly { name: string; geometry: CustomGeometry }[] = [
  {
    name: "Astral flame II",
    geometry: {
      x: "(0.08+1.05*b)*(0.74+0.26*sin(19*b-0.65*t))*sqrt(c)*cos(a*tau+9*b-0.25*t)+0.32*b*sin(8*b-0.45*t)",
      y: "3.5*b-1.75+0.18*b*sin(2*a*tau+9*b-0.45*t)",
      z: "(0.08+0.95*b)*(0.74+0.26*sin(19*b-0.65*t))*sqrt(c)*sin(a*tau+9*b-0.25*t)+0.24*b*cos(7*b-0.4*t)",
    },
  },
  {
    name: "Planet",
    geometry: {
      x: "2 * sqrt(1 - (2*b-1)*(2*b-1)) * cos(a*tau)",
      y: "2 * (2*b-1)",
      z: "2 * sqrt(1 - (2*b-1)*(2*b-1)) * sin(a*tau)",
    },
  },
  {
    name: "Glacial Hymn",
    geometry: {
      x: "(2*a-1)*(0.55+0.35*smoothstep(0.58,1,fract(b+0.07*t)))+0.18*sin(7*fract(b+0.07*t))+0.035*(2*c-1)",
      y: "1.35-2.55*smoothstep(0.3,0.56,fract(b+0.07*t))+0.035*sin(30*fract(b+0.07*t)+12*a)+0.08*(2*c-1)*(0.2+exp(-180*pow(fract(b+0.07*t)-0.59,2)))",
      z: "-1.8+3.6*fract(b+0.07*t)-0.62*smoothstep(0.3,0.43,fract(b+0.07*t))+0.62*smoothstep(0.46,0.62,fract(b+0.07*t))+0.025*sin(22*a+3*t)",
    },
  },
  {
    name: "Wildwood Waltz",
    geometry: {
      x: "mix(1.55*sqrt(min(b/0.65,1))*(1+0.045*sin(7*a*tau+0.4*t)),0.19+0.045*sin(3*a*tau+9*b),floor(b+0.35))*cos(a*tau)+0.12*sin(0.6*t+2*b)+0.025*(c-0.5)",
      y: "mix(0.55+0.95*sqrt(max(0,1-b/0.65))+0.06*sin(7*a*tau+0.4*t)*min(b/0.65,1),0.55-2.1*(b-0.65)/0.35,floor(b+0.35))+0.035*(c-0.5)+0.06*sin(0.7*t)",
      z: "mix(1.55*sqrt(min(b/0.65,1))*(1+0.045*sin(7*a*tau+0.4*t)),0.19+0.045*sin(3*a*tau+9*b),floor(b+0.35))*sin(a*tau)+0.08*cos(0.5*t+2*b)+0.025*(c-0.5)",
    },
  },
  {
    name: "Wholehearted",
    geometry: {
      x: "1.6*sin(a*tau)*sin(a*tau)*sin(a*tau)*sqrt(b)*(1+0.065*sin(5*t)+0.025*sin(10*t))",
      y: "0.1*(13*cos(a*tau)-5*cos(2*a*tau)-2*cos(3*a*tau)-cos(4*a*tau))*sqrt(b)*(1+0.065*sin(5*t)+0.025*sin(10*t))",
      z: "0.65*sqrt(1-b)*(2*c-1)*(1+0.065*sin(5*t)+0.025*sin(10*t))",
    },
  },
  {
    name: "Quiet Smoke",
    geometry: {
      x: "(0.1+0.85*b)*(0.74+0.26*sin(19*b-0.65*t))*sqrt(c)*cos(a*tau+9*b-0.25*t)+0.32*b*sin(8*b-0.45*t)",
      y: "3.5*b-1.75+0.18*b*sin(2*a*tau+9*b-0.45*t)",
      z: "(0.1+0.75*b)*(0.74+0.26*sin(19*b-0.65*t))*sqrt(c)*sin(a*tau+9*b-0.25*t)+0.24*b*cos(7*b-0.4*t)",
    },
  },
  {
    name: "Sapphire Veil",
    geometry: {
      x: "mix((2*a-1)*(0.86+0.22*pow(fract(b+0.23*t),2))+0.025*sin(80*a+12*fract(b+0.23*t)-t),1.75*sqrt(b)*cos(tau*a),smoothstep(0.8,0.84,c))",
      y: "mix(1.9-3.48*pow(fract(b+0.23*t),1.55),-1.59+0.13*sin(18*sqrt(b)-2.4*t)*exp(-2.5*b)+0.035*(2*c-1),smoothstep(0.8,0.84,c))",
      z: "mix(-0.28+0.76*pow(fract(b+0.23*t),3)+0.12*cos(tau*a)+0.035*sin(95*a+16*fract(b+0.23*t)-1.4*t)+0.1*(2*c-1),0.48+1.05*sqrt(b)*sin(tau*a),smoothstep(0.8,0.84,c))",
    },
  },
  {
    name: "Solar Fury",
    geometry: {
      x: "(1.42+0.025*sin(88*b-3*t)*cos(14*tau*a+1.2*t)+1.08*pow(c,8)*pow(0.5+0.5*sin(7*tau*a+18*b-2.2*t),8)+0.1*(c-0.5))*sqrt(1-(2*b-1)*(2*b-1))*cos(a*tau)",
      y: "(1.42+0.025*sin(88*b-3*t)*cos(14*tau*a+1.2*t)+1.08*pow(c,8)*pow(0.5+0.5*sin(7*tau*a+18*b-2.2*t),8)+0.1*(c-0.5))*(2*b-1)",
      z: "(1.42+0.025*sin(88*b-3*t)*cos(14*tau*a+1.2*t)+1.08*pow(c,8)*pow(0.5+0.5*sin(7*tau*a+18*b-2.2*t),8)+0.1*(c-0.5))*sqrt(1-(2*b-1)*(2*b-1))*sin(a*tau)",
    },
  },
  {
    name: "Tideglass",
    geometry: {
      x: "1.8*sqrt(a)*cos(b*tau)",
      y: "0.22*sin(24*sqrt(a)-3*t)*exp(-1.3*sqrt(a))+0.025*(2*c-1)",
      z: "1.8*sqrt(a)*sin(b*tau)",
    },
  },
  {
    name: "Breezewood",
    geometry: {
      x: "min(1,floor(12*a))*(1.75-0.09*floor(12*a))*mix(b,0.7+0.3*b,floor(c+0.7))*cos(2.4*floor(12*a)+0.045*sin(t+floor(12*a)))+(0.07*(1-0.8*b)+(0.26+0.18*c)*floor(c+0.7)*sin(pi*b))*cos(12*tau*a+0.14*sin(2*t+40*c))+0.045*b*b*sin(0.7*t)",
      y: "mix(-1.7+3.35*mix(b,0.7+0.3*b,floor(c+0.7)),-0.85+0.13*floor(12*a)+0.95*pow(mix(b,0.7+0.3*b,floor(c+0.7)),1.4),min(1,floor(12*a)))+0.28*floor(c+0.7)*sin(pi*b)*sin(12*tau*a+0.14*sin(2*t+40*c))+0.025*b*sin(0.8*t+floor(12*a))",
      z: "min(1,floor(12*a))*(1.75-0.09*floor(12*a))*mix(b,0.7+0.3*b,floor(c+0.7))*sin(2.4*floor(12*a)+0.045*sin(t+floor(12*a)))+(0.07*(1-0.8*b)+(0.26+0.18*c)*floor(c+0.7)*sin(pi*b))*sin(12*tau*a+0.14*sin(2*t+40*c))+0.03*b*b*cos(0.6*t)",
    },
  },
  {
    name: "Roseglass Reverie",
    geometry: {
      x: "mix(1.75*b*(0.68+0.32*cos(8*a*tau))*(1+0.025*sin(t*0.65+8*a*tau)),0.24*sqrt(b),smoothstep(0.79,0.81,c))*cos(a*tau)",
      y: "mix(-0.32+1.12*b*b-0.95*pow(b,4)+0.15*b*b*(1-cos(8*a*tau))+0.045*b*sin(t*0.8+8*a*tau),-0.26+0.48*b+0.05*sin(16*a*tau),smoothstep(0.79,0.81,c))",
      z: "mix(1.75*b*(0.68+0.32*cos(8*a*tau))*(1+0.025*sin(t*0.65+8*a*tau)),0.24*sqrt(b),smoothstep(0.79,0.81,c))*sin(a*tau)",
    },
  },
  {
    name: "Blush of Dawn",
    geometry: {
      x: "mix(1.85*sqrt(b)*(0.36+0.64*pow(0.5+0.5*cos(8*a*tau),0.65))*pow(0.74,floor(3*c))*(1+0.02*sin(0.65*t))*cos(a*tau+0.24*floor(3*c)),0.23*sqrt(b)*cos(a*tau),smoothstep(0.9,0.92,c))",
      y: "mix(-0.38+0.14*floor(3*c)+0.75*b-0.24*b*b+0.12*b*(1-cos(8*a*tau))+0.025*b*sin(0.65*t+8*a*tau),-0.06+0.28*sqrt(1-b)+0.018*sin(21*a*tau),smoothstep(0.9,0.92,c))",
      z: "mix(1.85*sqrt(b)*(0.36+0.64*pow(0.5+0.5*cos(8*a*tau),0.65))*pow(0.74,floor(3*c))*(1+0.02*sin(0.65*t))*sin(a*tau+0.24*floor(3*c)),0.23*sqrt(b)*sin(a*tau),smoothstep(0.9,0.92,c))",
    },
  },
  {
    name: "Molten Basin",
    geometry: {
      x: "mix(mix(1.65*b*cos(a*tau),(0.264+1.43*fract(b+0.11*t))*sin(0.22*sin(7*fract(b+0.11*t))+(0.34+0.38*fract(b+0.11*t))*(a-0.5)),floor(c+0.48)),0.12+1.08*sqrt(b)*cos(a*tau+0.025*t),floor(c+0.2))",
      y: "mix(mix(1.6-2.5*b-0.65*exp(-pow(9*b,2)),1.625-2.5*min(0.16+0.8666667*fract(b+0.11*t),1.014)-0.65*exp(-pow(9*(0.16+0.8666667*fract(b+0.11*t)),2)),floor(c+0.48)),-0.91+0.018*sin(15*sqrt(b)-0.8*t)+0.008*sin(6*a*tau+0.4*t),floor(c+0.2))",
      z: "mix(mix(0.3+1.65*b*sin(a*tau),0.3-(0.264+1.43*fract(b+0.11*t))*cos(0.22*sin(7*fract(b+0.11*t))+(0.34+0.38*fract(b+0.11*t))*(a-0.5)),floor(c+0.48)),-1.74+0.8*sqrt(b)*sin(a*tau+0.025*t),floor(c+0.2))",
    },
  },
];
