import { performable, type ParticleLook } from "./particleLooks";
/**
 * Particles Designer studies in the factory catalog. They follow the sixteen
 * PARTICLE_LOOKS, starting at P2 (see particleFactory.ts).
 */
export const PARTICLE_STUDIES: readonly ParticleLook[] = (<ParticleLook[]>[
  {
    id: "solar-system",
    name: "Solar system",
    description: "A golden sun, eight orbiting planets, Saturn's rings and fine orbital dust.",
    formation: 16,
    view: [-12, 38, -8, 7.2],
    settings: {
      "Particle density": 0.9,
      "Particle thickness": 0.18,
      Expansion: 0.88,
      "Particle dispersion": 0,
      Turbulence: 0,
      Light: 0.72,
      "Color variety": 1,
      "Color drift": 0,
      "Halo glow": 0.24,
      "Depth softness": 0.06,
      "Focus plane": 0.5,
      "Ribbon brightness": 0,
      Motion: 0.2,
    },
  },
  ...[
    {
      id: "earth-moon",
      name: "Earth & Moon",
      formation: 17,
      view: [-24, 12, -14, 5.7] as [number, number, number, number],
      description: "Blue oceans, green continents, bright cloud wisps and a softly orbiting moon.",
    },
    {
      id: "jovian-giant",
      name: "Jovian giant",
      formation: 18,
      view: [-42, 8, -16, 4.6] as [number, number, number, number],
      description: "A warm gas giant with turbulent cream and copper bands and a great red storm.",
    },
    {
      id: "saturn",
      name: "Saturn",
      formation: 19,
      view: [-12, 24, -22, 5.4] as [number, number, number, number],
      description: "A golden gas giant surrounded by fine icy rings and dark ring divisions.",
    },
    {
      id: "infinite-black-hole",
      name: "Infinite black hole",
      formation: 20,
      view: [0, 10, 10, 5.8] as [number, number, number, number],
      description: "An endlessly flowing accretion disk and luminous bent arc around a dark heart.",
    },
  ].map((look) => ({
    ...look,
    settings: {
      "Particle density": 0.95,
      "Particle thickness": look.formation === 20 ? 0.16 : 0.42,
      Expansion: 0.85,
      "Particle dispersion": 0,
      Turbulence: 0,
      Light: 0.9,
      "Color variety": 1,
      "Color drift": 0,
      "Halo glow": look.formation === 20 ? 0.5 : 0.1,
      "Depth softness": 0.04,
      "Focus plane": 0.5,
      "Ribbon brightness": 0,
      Motion: look.formation === 20 ? 0.35 : 0.12,
      "Rotation Y": look.formation === 18 ? 0.035 : 0,
    },
  })),
  ...[
    {
      id: "cosmic-lotus",
      name: "Cosmic lotus",
      formation: 21,
      view: [12, 38, 0, 5.4] as [number, number, number, number],
      description: "Three tiers of translucent nebula petals breathe around a golden pearl.",
    },
    {
      id: "celestial-eye",
      name: "Celestial eye",
      formation: 22,
      view: [0, 0, -5, 5.4] as [number, number, number, number],
      description: "An intricate turquoise and violet iris inside a fine golden celestial eye.",
    },
    {
      id: "astral-portal",
      name: "Astral portal",
      formation: 23,
      view: [12, 8, 0, 5.1] as [number, number, number, number],
      description:
        "Twelve counter-rotating luminous gates recede into a mysterious violet passage.",
    },
    {
      id: "eclipse-crown",
      name: "Eclipse crown",
      formation: 24,
      view: [0, 0, 0, 5.4] as [number, number, number, number],
      description: "A dark sun crowned by breathing gold filaments and long ember tendrils.",
    },
  ].map((look) => ({
    ...look,
    settings: {
      "Particle density": 0.88,
      "Particle thickness": look.formation === 23 ? 0.16 : 0.24,
      Expansion: 0.86,
      "Particle dispersion": 0,
      Turbulence: 0,
      Light: 0.78,
      "Color variety": 2.5,
      "Color drift": 0,
      "Halo glow": 0.32,
      "Depth softness": 0.08,
      "Focus plane": 0.5,
      "Ribbon brightness": 0.12,
      "Ribbon length": 0.25,
      Motion: 0.22,
    },
  })),
  {
    id: "aether-storm",
    name: "Aether storm",
    description:
      "Six flowing nebula ribbons, gyroscopic light rings and a radiant heart suspended in stardust.",
    formation: 25,
    view: [-12, 34, -12, 6.4],
    shockEnabled: true,
    settings: {
      "Particle density": 0.92,
      "Particle thickness": 0.22,
      Expansion: 0.88,
      "Particle dispersion": 0.006,
      Turbulence: 0.025,
      Light: 0.85,
      "Color variety": 2.5,
      "Color drift": 0,
      "Halo glow": 0.35,
      "Depth softness": 0.12,
      "Focus plane": 0.5,
      "Ribbon brightness": 0,
      "Ribbon length": 0.5,
      Motion: 0.3,
      "Rotation Y": 0.025,
      "Audio depth": 0.35,
      Shockwave: 0.45,
      Implosion: 0.65,
      Explosion: 0.45,
      "Recovery time": 0.65,
    },
  },
  ...[
    {
      id: "liquid-mercury",
      name: "Liquid mercury",
      formation: 26,
      view: [15, 12, -8, 4.7] as [number, number, number, number],
      description:
        "A flowing silver-blue liquid sculpture with rippling reflections and suspended droplets.",
    },
    {
      id: "astral-flame",
      name: "Astral flame",
      formation: 27,
      view: [0, 0, 0, 5.8] as [number, number, number, number],
      description: "Seven curling tongues of golden fire, a blue base and slowly rising embers.",
    },
  ].map((look) => ({
    ...look,
    settings: {
      "Particle density": 0.9,
      "Particle thickness": look.formation === 26 ? 0.38 : 0.22,
      Expansion: 0.88,
      "Particle dispersion": look.formation === 26 ? 0 : 0.012,
      Turbulence: 0,
      Light: 0.85,
      "Color variety": 1,
      "Color drift": 0,
      "Halo glow": look.formation === 26 ? 0.12 : 0.3,
      "Depth softness": 0.06,
      "Focus plane": 0.5,
      "Ribbon brightness": 0,
      Motion: look.formation === 26 ? 0.3 : 0.5,
      "Audio depth": 0.22,
    },
  })),
  {
    id: "silken-currents",
    name: "Silken currents",
    description:
      "Fine blue and champagne filaments braid into broad flowing currents, carrying tiny pearl lights.",
    formation: 28,
    shockEnabled: false,
    audioEnabled: false,
    attractorsEnabled: false,
    view: [-15.7, -15.4, 6, 5.52],
    settings: {
      "Particle density": 2,
      "Particle thickness": 0.92,
      Expansion: 3.8,
      "Particle dispersion": 0.08,
      Turbulence: 0.78,
      Light: 0.06,
      "Color variety": 1,
      "Color drift": 0.01,
      "Halo glow": 0,
      "Depth softness": 0.59,
      "Focus plane": 0.45,
      "Ribbon brightness": 0.23,
      "Ribbon length": 8,
      "Trail head size": 3.91,
      "Trail thickness": 16,
      Motion: 0.18,
      "Audio depth": 0.18,
      Attraction: 0,
      "Attractor separation": 0.65,
      "Attractor orbit": 0.3,
      "Rotation X": 0,
      "Rotation Y": 0,
      "Rotation Z": 0,
      Shockwave: 0.7,
      Implosion: 0.9,
      Explosion: 0.65,
      "Recovery time": 0.45,
    },
  },
  {
    id: "astral-veil",
    name: "Astral veil",
    description:
      "Rose and turquoise silken veils twist around orbiting attractors, with soft luminous heads and long flowing trails.",
    formation: 28,
    shockEnabled: false,
    audioEnabled: false,
    attractorsEnabled: true,
    view: [130.9, -120.8, 145.1, 8],
    settings: {
      "Particle density": 0.85,
      "Particle thickness": 0.92,
      Expansion: 3.8,
      "Particle dispersion": 0,
      Turbulence: 0,
      Light: 0.04,
      "Color variety": 5,
      "Color drift": 0.9,
      "Halo glow": 0,
      "Depth softness": 0.55,
      "Focus plane": 0.67,
      "Ribbon brightness": 0.17,
      "Ribbon length": 4.18,
      "Trail head size": 3.02,
      "Trail thickness": 16,
      Motion: 0.58,
      "Audio depth": 0.18,
      Attraction: 0.22,
      "Attractor separation": 1,
      "Attractor orbit": 1,
      "Rotation X": 0,
      "Rotation Y": 0,
      "Rotation Z": 0.08,
      Shockwave: 0.7,
      Implosion: 0.9,
      Explosion: 0.65,
      "Recovery time": 0.45,
    },
  },
  {
    id: "sahara-drift",
    name: "Sahara drift",
    description:
      "Golden crescent dunes with wind-driven sand, fine ripples and sunlit drifting grains.",
    formation: 29,
    shockEnabled: false,
    audioEnabled: false,
    attractorsEnabled: false,
    view: [-18, 32, -5, 6.5],
    settings: {
      "Particle density": 1.5,
      "Particle thickness": 0.25,
      Expansion: 0.85,
      "Particle dispersion": 0,
      Turbulence: 0,
      Light: 0.85,
      "Color variety": 1,
      "Color drift": 0,
      "Halo glow": 0.08,
      "Depth softness": 0.08,
      "Focus plane": 0.55,
      "Ribbon brightness": 0.07,
      "Ribbon length": 0.12,
      "Trail head size": 1,
      "Trail thickness": 0.6,
      Motion: 0.45,
      "Rotation X": 0,
      "Rotation Y": 0,
      "Rotation Z": 0,
    },
  },
]).map(performable);
