/** Designer control sections that can be switched off as a whole. */
export const PARTICLE_LOOK_GROUPS = [
  "particles",
  "light",
  "ribbons",
  "attractors",
  "motion",
  "shock",
  "cycle",
  "audio",
] as const;
export type ParticleLookGroups = Record<(typeof PARTICLE_LOOK_GROUPS)[number], boolean>;
/** Shared authored particle looks. Runtime scenes always receive copies. */
export interface ParticleLook {
  id: string;
  name: string;
  description: string;
  formation: number;
  shockEnabled?: boolean;
  audioEnabled?: boolean;
  attractorsEnabled?: boolean;
  settings: Record<string, number>;
  view: [number, number, number, number]; // yaw, pitch, roll degrees; distance
  /** One to six "#rrggbb" colors ordered along the shape; absent = built-in colors. */
  palette?: string[];
  /** Section switches (absent sections follow the Designer defaults). */
  groups?: ParticleLookGroups;
  /** Designer-only: audio transients trigger the collapse cycle. */
  cycleAudio?: boolean;
  /** Optional shape mixture; hosts without blending render the dominant `formation`. */
  formationWeights?: number[];
}
export const PARTICLE_LOOKS: readonly ParticleLook[] = [
  {
    id: "deep-sea",
    name: "Deep sea",
    description: "A luminous jellyfish with flowing tendrils and blue, violet and pink light.",
    formation: 14,
    shockEnabled: true,
    view: [10.2, 18.9, 0, 5.8],
    settings: {
      "Particle density": 0.58,
      "Particle thickness": 0.22,
      Expansion: 0.68,
      "Particle dispersion": 0,
      Turbulence: 0.17,
      Light: 0.45,
      "Color variety": 2.2,
      "Color drift": 0.08,
      "Halo glow": 0.5,
      "Depth softness": 0.26,
      "Focus plane": 0.5,
      "Ribbon brightness": 0.81,
      "Ribbon length": 0.62,
      Attraction: 0,
      "Attractor separation": 0.65,
      "Attractor orbit": 0.3,
      Motion: 0.76,
      "Rotation X": 0,
      "Rotation Y": 0,
      "Rotation Z": 0,
      Shockwave: 0.7,
      Implosion: 0.9,
      Explosion: 0.65,
      "Recovery time": 0.45,
      "Audio depth": 0,
    },
  },
  {
    id: "galaxy-drift",
    name: "Galaxy drift",
    description: "A broad luminous galaxy with fine dust, flowing ribbons and a slow orbital turn.",
    formation: 4,
    view: [-8.1, 33.2, -22, 3],
    settings: {
      "Particle density": 0.79,
      "Particle thickness": 0.33,
      Expansion: 1.31,
      "Particle dispersion": 0.02,
      Turbulence: 0.05,
      Light: 0.92,
      "Color drift": 0.52,
      "Color variety": 0.64,
      "Halo glow": 0.29,
      "Depth softness": 0.64,
      "Focus plane": 0.49,
      "Ribbon length": 0.6,
      "Ribbon brightness": 0.45,
      Attraction: 0,
      "Attractor separation": 0.65,
      "Attractor orbit": 0.3,
      Motion: 0.22,
      "Rotation X": 0,
      "Rotation Y": 0.04,
      "Rotation Z": 0,
      Implosion: 0.9,
      Explosion: 0.65,
      "Recovery time": 0.45,
      "Audio depth": 0,
    },
  },
  {
    id: "moon-dunes",
    name: "Moon dunes",
    description: "Silver-blue mountain ridges, wind-shaped slopes and fine sand ripples.",
    formation: 15,
    view: [-18, 32, 0, 5.6],
    settings: {
      "Particle density": 0.75,
      "Particle thickness": 0.15,
      "Color variety": 0,
      "Color drift": 0,
      "Halo glow": 0.2,
      "Depth softness": 0.1,
      "Ribbon brightness": 0,
      Motion: 0.2,
      Turbulence: 0,
    },
  },
  {
    id: "neon-weave",
    name: "Neon weave",
    description: "A bright multicolored trefoil with fine trailing ribbons.",
    formation: 5,
    view: [25, 30, 10, 4.7],
    settings: {
      "Particle density": 0.5,
      "Particle thickness": 0.22,
      "Color variety": 4,
      "Halo glow": 0.4,
      "Ribbon brightness": 0.55,
      "Ribbon length": 0.5,
      Motion: 0.3,
      Turbulence: 0.1,
      "Rotation Y": 0.1,
    },
  },
  {
    id: "sunset-ridges",
    name: "Sunset ridges",
    description: "Warm amber mountain crests, deep valleys and drifting sand.",
    formation: 15,
    view: [-32, 24, -4, 5.8],
    settings: {
      "Particle density": 0.9,
      "Particle thickness": 0.22,
      Expansion: 0.72,
      "Particle dispersion": 0.015,
      Turbulence: 0,
      Light: 0.8,
      "Color variety": 0.25,
      "Color drift": 0.48,
      "Halo glow": 0.34,
      "Depth softness": 0.12,
      "Focus plane": 0.45,
      "Ribbon brightness": 0,
      Motion: 0.16,
    },
  },
  {
    id: "glacial-peaks",
    name: "Glacial peaks",
    description: "A sweeping glacial panorama with crisp cyan peaks and violet shadows.",
    formation: 15,
    view: [48, 38, 0, 6.2],
    settings: {
      "Particle density": 0.85,
      "Particle thickness": 0.18,
      Expansion: 0.9,
      Turbulence: 0,
      Light: 0.75,
      "Color variety": 0.12,
      "Color drift": 0.02,
      "Halo glow": 0.2,
      "Depth softness": 0.18,
      "Focus plane": 0.6,
      "Ribbon brightness": 0,
      Motion: 0.06,
    },
  },
  {
    id: "northern-lights",
    name: "Northern lights",
    description: "Slow green, purple and blue curtains seen from below.",
    formation: 13,
    view: [-12, -9, 180, 4.8],
    settings: {
      "Particle density": 0.88,
      "Particle thickness": 0.38,
      Expansion: 1.05,
      "Particle dispersion": 0.01,
      Turbulence: 0,
      Light: 0.85,
      "Color variety": 2.2,
      "Color drift": 0,
      "Halo glow": 0.55,
      "Depth softness": 0.24,
      "Focus plane": 0.4,
      "Ribbon brightness": 0.75,
      "Ribbon length": 0.85,
      Motion: 0.24,
    },
  },
  {
    id: "prism-cathedral",
    name: "Prism cathedral",
    description: "Intersecting luminous arches, six colors and a slow axial turn.",
    formation: 8,
    view: [24, 18, 30, 4.8],
    settings: {
      "Particle density": 0.55,
      "Particle thickness": 0.18,
      Expansion: 0.9,
      Turbulence: 0.015,
      Light: 0.65,
      "Color variety": 5,
      "Color drift": 0.08,
      "Halo glow": 0.48,
      "Depth softness": 0.14,
      "Ribbon brightness": 0.5,
      "Ribbon length": 0.7,
      Motion: 0.18,
      "Rotation Y": 0.06,
    },
  },
  {
    id: "ember-shell",
    name: "Ember shell",
    description: "A glowing spiral shell with a red-gold core and trailing embers.",
    formation: 9,
    view: [-28, 32, -22, 4.9],
    settings: {
      "Particle density": 0.65,
      "Particle thickness": 0.24,
      Expansion: 0.85,
      "Particle dispersion": 0.045,
      Turbulence: 0.05,
      Light: 0.7,
      "Color variety": 0.32,
      "Color drift": 0.52,
      "Halo glow": 0.5,
      "Depth softness": 0.25,
      "Focus plane": 0.38,
      "Ribbon brightness": 0.45,
      "Ribbon length": 0.6,
      Motion: 0.22,
      "Rotation Y": 0.04,
    },
  },
  {
    id: "electric-bloom",
    name: "Electric bloom",
    description: "A violet and turquoise flower opening in a haze of fine filaments.",
    formation: 7,
    view: [8, 58, 12, 4.5],
    settings: {
      "Particle density": 0.6,
      "Particle thickness": 0.2,
      Expansion: 0.82,
      "Particle dispersion": 0.035,
      Turbulence: 0.06,
      Light: 0.7,
      "Color variety": 2.7,
      "Color drift": 0.08,
      "Halo glow": 0.48,
      "Depth softness": 0.2,
      "Ribbon brightness": 0.35,
      "Ribbon length": 0.5,
      Motion: 0.25,
      "Rotation Z": 0.025,
    },
  },
  {
    id: "event-horizon",
    name: "Event horizon",
    description: "A tilted incandescent vortex with a dark heart and long orbital filaments.",
    formation: 0,
    view: [12, 68, -28, 4.8],
    settings: {
      "Particle density": 0.72,
      "Particle thickness": 0.2,
      Expansion: 0.9,
      "Particle dispersion": 0.025,
      Turbulence: 0.08,
      Light: 0.75,
      "Color variety": 0.3,
      "Color drift": 0.49,
      "Halo glow": 0.5,
      "Depth softness": 0.22,
      "Focus plane": 0.45,
      "Ribbon brightness": 0.65,
      "Ribbon length": 0.9,
      Motion: 0.4,
    },
  },
  {
    id: "pearl-planet",
    name: "Pearl planet",
    description: "An opalescent shell with a crisp luminous rim and a slow planetary turn.",
    formation: 1,
    view: [-18, 12, 8, 4.2],
    settings: {
      "Particle density": 0.7,
      "Particle thickness": 0.12,
      Expansion: 0.75,
      "Particle dispersion": 0.01,
      Turbulence: 0,
      Light: 0.65,
      "Color variety": 0.15,
      "Color drift": 0,
      "Halo glow": 0.35,
      "Depth softness": 0.35,
      "Focus plane": 0.38,
      "Ribbon brightness": 0.12,
      "Ribbon length": 0.25,
      Motion: 0.12,
      "Rotation Y": 0.035,
    },
  },
  {
    id: "mercury-tide",
    name: "Mercury tide",
    description: "Low blue waves with fine trailing foam and a glancing shoreline view.",
    formation: 2,
    view: [-24, 26, 0, 5.2],
    settings: {
      "Particle density": 0.8,
      "Particle thickness": 0.15,
      Expansion: 0.88,
      "Particle dispersion": 0.025,
      Turbulence: 0.06,
      Light: 0.72,
      "Color variety": 0.1,
      "Color drift": 0.94,
      "Halo glow": 0.25,
      "Depth softness": 0.16,
      "Focus plane": 0.6,
      "Ribbon brightness": 0.35,
      "Ribbon length": 0.4,
      Motion: 0.3,
    },
  },
  {
    id: "cosmic-dna",
    name: "Cosmic DNA",
    description: "Two neon strands winding through one another in violet and cyan.",
    formation: 3,
    view: [22, 5, 24, 4.7],
    settings: {
      "Particle density": 0.58,
      "Particle thickness": 0.2,
      Expansion: 0.78,
      "Particle dispersion": 0.025,
      Turbulence: 0.03,
      Light: 0.65,
      "Color variety": 2.2,
      "Color drift": 0.07,
      "Halo glow": 0.45,
      "Depth softness": 0.2,
      "Ribbon brightness": 0.55,
      "Ribbon length": 0.65,
      Motion: 0.25,
      "Rotation Y": 0.055,
    },
  },
  {
    id: "silk-orbit",
    name: "Silk orbit",
    description: "A flowing half-twisted ribbon with warm highlights and soft optical glow.",
    formation: 6,
    view: [-22, 42, -20, 4.6],
    settings: {
      "Particle density": 0.62,
      "Particle thickness": 0.18,
      Expansion: 0.88,
      "Particle dispersion": 0.025,
      Turbulence: 0.02,
      Light: 0.65,
      "Color variety": 0.6,
      "Color drift": 0.46,
      "Halo glow": 0.38,
      "Depth softness": 0.3,
      "Focus plane": 0.45,
      "Ribbon brightness": 0.4,
      "Ribbon length": 0.55,
      Motion: 0.16,
      "Rotation Y": 0.03,
    },
  },
  {
    id: "crystal-city",
    name: "Crystal city",
    description: "A precise cyan lattice seen in perspective, with deep layers of luminous edges.",
    formation: 11,
    view: [34, 25, 0, 4.9],
    settings: {
      "Particle density": 0.6,
      "Particle thickness": 0.12,
      Expansion: 0.82,
      "Particle dispersion": 0,
      Turbulence: 0,
      Light: 0.62,
      "Color variety": 0.25,
      "Color drift": 0.94,
      "Halo glow": 0.32,
      "Depth softness": 0.1,
      "Focus plane": 0.55,
      "Ribbon brightness": 0.12,
      "Ribbon length": 0.25,
      Motion: 0.08,
      "Rotation Y": 0.025,
    },
  },
];
